#!/bin/bash

echo "🚀 === 手動推送到 GitHub 教學 ==="
echo ""
echo "如果您已經在 GitHub 建立了儲存庫，請執行以下命令："
echo ""
echo "# 請將 YOUR_USERNAME 替換成您的 GitHub 用戶名"
echo "GITHUB_USER=\"YOUR_USERNAME\""
echo "REPO_NAME=\"taiwan-stock-data-collector\""
echo ""
echo "# 添加遠端儲存庫"
echo "git remote add origin https://github.com/\${GITHUB_USER}/\${REPO_NAME}.git"
echo ""
echo "# 推送主分支"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "# 推送標籤"
echo "git push origin --tags"
echo ""
echo "# 推送其他分支"
echo "git push origin develop"
echo "git push origin feature/data-collection"
echo "git push origin feature/api-monitoring"
echo "git push origin hotfix/ready"
echo ""
echo "🎉 推送完成後，您可以在以下網址查看專案："
echo "https://github.com/\${GITHUB_USER}/\${REPO_NAME}"